export const IMAGE_MAP_UPDATE_EVENT = 'image-map-update'
export const IMAGE_MINI_MAP_UPDATE_EVENT = 'image-mini-map-update'
export const HEX_MAP_UPDATE_EVENT = 'hex-map-update'
export const HEX_MINI_MAP_UPDATE_EVENT = 'hex-mini-map-update'
export const LEFT_PANEL_TOGGLE_EVENT = 'toggle-left-panel'
export const RIGHT_PANEL_TOGGLE_EVENT = 'toggle-right-panel'
export const LAYER_CHANGE_EVENT = 'layer-change'
